server {
    listen 80;
    server_name darshgobus.baby www.darshgobus.baby;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name darshgobus.baby www.darshgobus.baby;

    ssl_certificate /etc/letsencrypt/live/darshgobus.baby/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/darshgobus.baby/privkey.pem;

    location /static/ {
        alias /app/staticfiles/;
        autoindex off;
        expires max;
        add_header Cache-Control public;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
    }
}

