# Generated by Django 5.1.4 on 2025-02-19 05:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='busdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_number', models.CharField(max_length=10)),
                ('depart_from', models.CharField(max_length=50)),
                ('stop1', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2025, 2, 19, 10, 48, 27, 820332))),
                ('totalseats', models.PositiveIntegerField()),
                ('availableseats', models.PositiveIntegerField(default=150)),
                ('fare', models.PositiveIntegerField()),
                ('seat_category', models.CharField(choices=[('GEN', 'general'), ('SLP', 'sleeper'), ('LXY', 'luxury')], default='GEN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=50)),
                ('stop_number', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('fare_from_start', models.PositiveIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='exp.busdetails')),
            ],
            options={
                'ordering': ['stop_number'],
                'unique_together': {('bus', 'stop_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('no_of_seats', models.PositiveIntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.busdetails')),
                ('destination_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_to', to='exp.busstop')),
                ('source_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_from', to='exp.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('age', models.PositiveIntegerField(default=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='exp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
