# Generated by Django 5.1.4 on 2024-12-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='clothes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='shoes',
            field=models.IntegerField(default=0),
        ),
    ]
