# Generated by Django 5.1.4 on 2025-02-22 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetails',
            name='depart_from',
        ),
        migrations.RemoveField(
            model_name='busdetails',
            name='stop1',
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 15, 26, 25, 587201)),
        ),
    ]
