# Generated by Django 5.1.4 on 2025-02-23 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_remove_busdetails_depart_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetails',
            name='availableseats',
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 16, 7, 37, 722038)),
        ),
    ]
