# Generated by Django 5.1.4 on 2025-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_expense_books_expense_clothes_expense_shoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='busdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_number', models.CharField(max_length=10)),
                ('depart_from', models.CharField(max_length=50)),
                ('stop1', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('totalseats', models.IntegerField()),
                ('fare', models.IntegerField()),
            ],
        ),
    ]
