# Generated by Django 4.2.20 on 2025-03-21 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_remove_busdetails_availableseats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 18, 56, 0, 309027)),
        ),
    ]
