# Generated by Django 5.1.4 on 2025-02-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0004_busdetails_date_booking_delete_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seat_no',
            new_name='no_of_seats',
        ),
        migrations.AddField(
            model_name='busdetails',
            name='availableseats',
            field=models.IntegerField(default=150),
        ),
    ]
