# Generated by Django 5.1.4 on 2025-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0005_rename_seat_no_booking_no_of_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='availableseats',
            field=models.IntegerField(default=150),
        ),
    ]
