# Generated by Django 4.2.20 on 2025-03-22 05:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exp', '0005_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='busadmin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 5, 55, 48, 748371)),
        ),
    ]
