# Generated by Django 4.2.20 on 2025-03-22 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0006_busdetails_busadmin_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 6, 1, 0, 973682)),
        ),
    ]
