# Generated by Django 5.1.4 on 2025-02-07 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0007_alter_booking_date_passenger_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='busdetails',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 14, 51, 45, 517563)),
        ),
    ]
