# Generated by Django 5.1.4 on 2025-02-07 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0008_remove_busdetails_date_remove_busdetails_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 15, 37, 21, 542058)),
        ),
    ]
