# Generated by Django 4.2.20 on 2025-03-12 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0008_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 14, 46, 9, 229865)),
        ),
    ]
