# Generated by Django 4.2.20 on 2025-03-22 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0008_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 9, 56, 57, 309753)),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='running_days',
            field=models.ManyToManyField(to='exp.runningday'),
        ),
    ]
