# Generated by Django 4.2.20 on 2025-03-23 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0010_alter_busdetails_date_time_alter_runningday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 8, 1, 46, 538496)),
        ),
    ]
