# Generated by Django 4.2.20 on 2025-04-03 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0012_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 20, 0, 5, 877862)),
        ),
    ]
