# Generated by Django 5.1.4 on 2025-02-13 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0018_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 22, 32, 10, 319806)),
        ),
    ]
