# Generated by Django 5.1.4 on 2025-02-13 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0019_passenger_seat_no_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 22, 37, 21, 704050)),
        ),
    ]
