# Generated by Django 4.2.20 on 2025-04-07 09:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exp', '0020_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='busadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 9, 6, 55, 441363)),
        ),
    ]
