# Generated by Django 5.1.4 on 2025-02-15 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0020_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='busdetails',
            name='seat_category',
            field=models.CharField(choices=[('GEN', 'general'), ('SLP', 'sleeper'), ('LXY', 'luxury')], default='GEN', max_length=3),
        ),
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 14, 19, 36, 279316)),
        ),
    ]
