# Generated by Django 5.1.4 on 2025-02-15 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0021_remove_passenger_seat_no_busdetails_seat_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 15, 12, 0, 128368)),
        ),
    ]
