# Generated by Django 4.2.20 on 2025-04-08 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0021_alter_booking_name_alter_busdetails_busadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 4, 52, 25, 981257)),
        ),
    ]
