# Generated by Django 5.1.4 on 2025-02-15 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0022_alter_busdetails_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 20, 10, 21, 846488)),
        ),
    ]
